<?php
/**
 * Live demo: the whole chain on one screen, for a stand at a trade fair.
 *
 *   1. the product and its code
 *   2. the page the finder opens
 *   3. the message the finder sends
 *   4. the inbox the owner reads, and the reply
 *   5. how to start your own tag
 *
 * Steps are switched by the URL fragment, so the page works with JavaScript
 * disabled, deep links survive and the operator can jump straight to a step.
 * Nothing here is a mockup: the QR code is generated by this installation, the
 * tag page is loaded live, and the inbox shows the messages that really arrived.
 */

if (!defined('LINKTEC_SECURE')) {
    define('LINKTEC_SECURE', true);
}

require_once __DIR__ . '/includes/bootstrap.php';

$entry = dat_demo_showcase_entry();
$assetRow = dat_demo_showcase_asset();

if ($entry === null) {
    http_response_code(500);
    exit('Demo data missing');
}

$publicUrl = dat_tag_url($entry['public_id']);
$qrSvg = dat_qr_svg($publicUrl, 8, 3);
$imageUrl = dat_product_image_url($entry['image']);
$nfcPayload = dat_nfc_payload($assetRow ?? dat_demo_asset_row($entry), $publicUrl);
$messages = dat_demo_recent_messages($entry['public_id'], 4);
$messageCount = dat_demo_message_count($entry['public_id']);
$typeMeta = dat_asset_type_meta($entry['type']);
$split = dat_demo_field_split($entry);

$board = dat_demo_entry('menu_board');
$wifiPayload = dat_wifi_qr_payload($board['metadata']['wifi_network'] ?? '', $board['metadata']['wifi_password'] ?? '');

/*
 * The other half of the product: a tag that is not about losing anything.
 * The menu board is the clearest example, its owner changes prices and the
 * daily menu and the printed code never has to change with them.
 */
$infoEntry = dat_demo_information_entry();
$infoUrl = dat_tag_url($infoEntry['public_id']);
$infoImage = dat_product_image_url($infoEntry['image']);
$infoTypeMeta = dat_asset_type_meta($infoEntry['type']);
$infoAsset = dat_asset_by_public_id($infoEntry['public_id']);
$infoEditUrl = $infoAsset !== null
    ? dat_url('dashboard/asset-edit.php') . '?id=' . rawurlencode($infoAsset['id'])
    : dat_url('account/login.php');
$infoFields = [];
foreach ($infoTypeMeta['fields'] as $field) {
    $infoFields[] = [
        'label' => $field['label'],
        'value' => (string) ($infoEntry['metadata'][$field['key']] ?? ''),
        'public' => !empty($field['public']),
    ];
}

$steps = [
    ['key' => '1', 'label' => t('demo.step1_nav', 'The tag')],
    ['key' => '2', 'label' => t('demo.step2_nav', 'The page')],
    ['key' => '3', 'label' => t('demo.step3_nav', 'The message')],
    ['key' => '4', 'label' => t('demo.step4_nav', 'The reply')],
    ['key' => '5', 'label' => t('demo.info_nav', 'Edit the page')],
    ['key' => '6', 'label' => t('demo.step5_nav', 'Your own tag')],
];

dat_page_start([
    'title' => t('demo.title', 'Live demo') . ' | ' . PORTAL_NAME,
    'description' => t('demo.meta', 'The whole chain in one walkthrough: tap a tag, open the page, send an anonymous message, read it in the owner inbox and reply.'),
    'canonical' => dat_url('demo'),
    'robots' => 'noindex, follow',
    'body_class' => 'is-demo',
    'unread' => 0,
]);
?>
<main id="main" class="demo">
    <?php if (PORTAL_DEMO_MODE): ?>
        <p class="demo-flag"><?= e(t('demo.mode_on', 'Booth mode: the per-IP limits that normally protect the form are lifted so a whole fair can try it.')) ?></p>
    <?php endif; ?>

    <nav class="demo-steps" aria-label="<?= e(t('demo.steps_label', 'Demo steps')) ?>">
        <?php foreach ($steps as $index => $step): ?>
            <a class="demo-step" href="#step-<?= e($step['key']) ?>"
               id="tab-step-<?= e($step['key']) ?>"
               role="tab"
               aria-controls="step-<?= e($step['key']) ?>"
               aria-selected="<?= $index === 0 ? 'true' : 'false' ?>"
               tabindex="<?= $index === 0 ? '0' : '-1' ?>">
                <span class="demo-step-index"><?= $index + 1 ?></span>
                <span class="demo-step-label"><?= e($step['label']) ?></span>
            </a>
        <?php endforeach; ?>
    </nav>

    <div class="demo-stages" data-tabs>
        <section class="demo-stage" id="step-1" role="tabpanel" aria-labelledby="tab-step-1" tabindex="0">
            <div class="demo-grid">
                <div class="demo-copy">
                    <p class="eyebrow"><?= e(t('demo.step1_eyebrow', 'Step 1 of 5')) ?></p>
                    <h1><?= e(t('demo.step1_title', 'One product, one permanent link')) ?></h1>
                    <p><?= e(sprintf(t('demo.step1_body', 'This is the %s from the catalogue. The chip and the printed code carry the same address, and nothing else: the details, the photos and the notes live on this server and can change at any time.'), $entry['name'])) ?></p>

                    <p class="demo-scan-hint">
                        <i class="fa-solid fa-mobile-screen-button" aria-hidden="true"></i>
                        <?= e(t('demo.step1_scan', 'Scan the code with the phone camera, or hold a phone against the chip.')) ?>
                    </p>

                    <dl class="demo-facts">
                        <div>
                            <dt><?= e(t('demo.public_url', 'Public address')) ?></dt>
                            <dd><code><?= e($publicUrl) ?></code></dd>
                        </div>
                        <div>
                            <dt><?= e(t('demo.payload', 'Text on the chip')) ?></dt>
                            <dd><pre class="nfc-sample"><?= e($nfcPayload) ?></pre></dd>
                        </div>
                        <div>
                            <dt><?= e(t('demo.on_the_page', 'On the page')) ?></dt>
                            <dd>
                                <?php foreach ($split['public'] as $label => $value): ?>
                                    <span class="demo-chip"><?= e($label) ?>: <?= e($value) ?></span>
                                <?php endforeach; ?>
                            </dd>
                        </div>
                    </dl>

                    <div class="demo-actions">
                        <a class="btn btn-primary btn-lg" href="#step-2"><?= e(t('demo.next', 'Next step')) ?></a>
                        <button type="button" class="btn btn-ghost btn-lg" data-print><?= e(t('demo.print_card', 'Print this card')) ?></button>
                    </div>

                    <div class="demo-print-only">
                        <p class="demo-print-brand"><?= e(PORTAL_NAME) ?></p>
                        <p><?= e(t('demo.print_intro', 'Scan the code, have a look at the page, send us a message.')) ?></p>
                        <ol>
                            <li><?= e(t('demo.print1', 'Scan the code with the phone camera, no app needed')) ?></li>
                            <li><?= e(t('demo.print2', 'The page shows what the product is, and to whom it belongs')) ?></li>
                            <li><?= e(t('demo.print3', 'Write one message, the owner sees it in their inbox')) ?></li>
                        </ol>
                    </div>
                </div>

                <div class="demo-visual">
                    <?php if ($imageUrl !== null): ?>
                        <figure class="product-shot"><img src="<?= e($imageUrl) ?>" alt="<?= e($entry['name']) ?>"></figure>
                    <?php endif; ?>
                    <div class="demo-qr">
                        <?= $qrSvg ?>
                        <p><?= e(t('demo.qr_note', 'Scannable, generated here, no third-party service')) ?></p>
                    </div>
                </div>
            </div>
        </section>

        <section class="demo-stage" id="step-2" role="tabpanel" aria-labelledby="tab-step-2" tabindex="0">
            <div class="demo-copy demo-copy-wide">
                <p class="eyebrow"><?= e(t('demo.step2_eyebrow', 'Step 2 of 5')) ?></p>
                <h2><?= e(t('demo.step2_title', 'What the finder sees')) ?></h2>
                <p><?= e(t('demo.step2_body', 'The page below is loaded live from this installation, exactly as it opens on a phone. No screenshot, no mockup.')) ?></p>
                <p class="demo-actions">
                    <a class="btn btn-ghost" href="<?= e($publicUrl) ?>" target="_blank" rel="noopener">
                        <?= e(t('demo.open_new_tab', 'Open in a new tab')) ?>
                        <i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-primary" href="#step-3"><?= e(t('demo.next', 'Next step')) ?></a>
                </p>
            </div>
            <div class="demo-frame">
                <div class="demo-frame-bar"><span></span><code><?= e($publicUrl) ?></code></div>
                <iframe src="<?= e($publicUrl) ?>" title="<?= e(t('demo.step2_title', 'What the finder sees')) ?>" loading="lazy"></iframe>
            </div>
        </section>

        <section class="demo-stage" id="step-3" role="tabpanel" aria-labelledby="tab-step-3" tabindex="0">
            <div class="demo-grid">
                <div class="demo-copy">
                    <p class="eyebrow"><?= e(t('demo.step3_eyebrow', 'Step 3 of 5')) ?></p>
                    <h2><?= e(t('demo.step3_title', 'The finder writes, without an account')) ?></h2>
                    <p><?= e(t('demo.step3_body', 'Send it for real. Your message goes into the inbox of the person who owns this demo tag, and it shows up in the next step. Nothing about you is stored: no name, no email address, no phone number.')) ?></p>

                    <form method="post" action="<?= e(dat_url('t/found.php')) ?>" class="form-card demo-form">
                        <?= dat_csrf_field() ?>
                        <input type="hidden" name="id" value="<?= e($entry['public_id']) ?>">
                        <div class="honeypot" aria-hidden="true">
                            <label for="reference"><?= e(t('form.reference', 'Reference')) ?></label>
                            <input type="text" id="reference" name="reference" tabindex="-1" autocomplete="off">
                        </div>
                        <div class="form-row">
                            <label for="message"><?= e(t('found.message_label', 'Your message')) ?></label>
                            <textarea id="message" name="message" maxlength="1000" required
                                      placeholder="<?= e(t('demo.step3_placeholder', 'I found a set of keys with your keychain at the entrance, I handed them in at the desk.')) ?>"><?= e(t('demo.step3_prefill', 'I found a set of keys with your keychain by the entrance. The reception desk has them.')) ?></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg">
                            <i class="fa-solid fa-paper-plane" aria-hidden="true"></i>
                            <?= e(t('found.submit', 'Send message')) ?>
                        </button>
                    </form>
                </div>

                <div class="demo-visual">
                    <div class="demo-note">
                        <h3><?= e(t('demo.step3_side_title', 'What the finder does not have to give')) ?></h3>
                        <ul class="tick-list">
                            <li><?= e(t('demo.step3_side1', 'No account, no app, no sign-up screen')) ?></li>
                            <li><?= e(t('demo.step3_side2', 'No name, email address or phone number')) ?></li>
                            <li><?= e(t('demo.step3_side3', 'One message, and then a private link to the answer')) ?></li>
                        </ul>
                        <p class="form-hint"><?= e(sprintf(t('demo.messages_so_far', 'Messages on this demo tag so far: %d'), $messageCount)) ?></p>
                    </div>
                    <p class="demo-actions">
                        <a class="btn btn-primary" href="#step-4"><?= e(t('demo.next', 'Next step')) ?></a>
                    </p>
                </div>
            </div>
        </section>

        <section class="demo-stage" id="step-4" role="tabpanel" aria-labelledby="tab-step-4" tabindex="0">
            <div class="demo-grid">
                <div class="demo-copy">
                    <p class="eyebrow"><?= e(t('demo.step4_eyebrow', 'Step 4 of 5')) ?></p>
                    <h2><?= e(t('demo.step4_title', 'The owner reads it and answers')) ?></h2>
                    <p><?= e(t('demo.step4_body', 'This is the owner inbox, live. Messages that arrive while we stand here appear at the top. The owner replies inside the portal, and the finder reads the answer on the private link they were given.')) ?></p>

                    <?php if ($messages): ?>
                        <ul class="demo-inbox">
                            <?php foreach ($messages as $message): ?>
                                <?php $fromOwner = (int) $message['direction'] === DAT_MESSAGE_DIRECTION_OWNER; ?>
                                <li class="<?= $fromOwner ? 'is-owner' : 'is-finder' ?>">
                                    <span class="demo-inbox-who"><?= e($fromOwner ? t('messages.you', 'You') : t('messages.finder', 'Finder')) ?></span>
                                    <span class="demo-inbox-text"><?= e(mb_substr(trim((string) $message['content']), 0, 200)) ?></span>
                                    <time datetime="<?= e($message['created_at']) ?>"><?= e(date('d.m.Y H:i', strtotime($message['created_at']))) ?></time>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <p class="form-hint"><?= e(t('demo.step4_empty', 'No messages yet. Send one in step 3 and it appears here.')) ?></p>
                    <?php endif; ?>

                    <p class="demo-actions">
                        <a class="btn btn-ghost" href="<?= e(dat_url('account/login.php')) ?>">
                            <?= e(t('demo.step4_login', 'Open the real dashboard')) ?>
                        </a>
                        <a class="btn btn-primary" href="#step-5"><?= e(t('demo.next', 'Next step')) ?></a>
                    </p>
                </div>

                <div class="demo-visual">
                    <div class="demo-note">
                        <h3><?= e(t('demo.step4_side_title', 'What the owner can do next')) ?></h3>
                        <ul class="tick-list">
                            <li><?= e(t('demo.step4_side1', 'Reply in the thread, or archive it')) ?></li>
                            <li><?= e(t('demo.step4_side2', 'Switch the asset to lost, found or active')) ?></li>
                            <li><?= e(t('demo.step4_side3', 'Replace a damaged tag without changing the link')) ?></li>
                        </ul>
                        <p class="form-hint"><?= e(t('demo.step4_side_note', 'Replies stay in the portal. Neither side has to hand over a phone number.')) ?></p>
                    </div>
                </div>
            </div>
        </section>

        <section class="demo-stage" id="step-5" role="tabpanel" aria-labelledby="tab-step-5" tabindex="0">
            <div class="demo-copy demo-copy-wide">
                <p class="eyebrow"><?= e(t('demo.info_eyebrow', 'Step 5 of 6')) ?></p>
                <h2><?= e(t('demo.info_title', 'Most tags are not about losing something')) ?></h2>
                <p><?= e(sprintf(t('demo.info_body', 'The %s is the other half of the product. Nothing has gone missing here. What changes is the information: the daily menu, the price of a dish, the opening hours, the guest Wi-Fi name, a new photo. The owner edits the page and the code on the board, printed months ago, opens the new version straight away.'), $infoEntry['name'])) ?></p>
                <p><?= e(t('demo.info_body2', 'That is why the tag page for this product offers "Add or edit information" instead of a lost-property form. Only the pet tag keeps the finder form.')) ?></p>
            </div>

            <div class="demo-grid">
                <div class="demo-copy">
                    <div class="demo-note">
                        <h3><?= e(t('demo.info_side_title', 'What the owner can add or change')) ?></h3>
                        <dl class="demo-facts">
                            <?php foreach ($infoFields as $field): ?>
                                <div>
                                    <dt>
                                        <?= e($field['label']) ?>
                                        <?php if (!$field['public']): ?>
                                            <span class="pill pill-neutral"><i class="fa-solid fa-lock" aria-hidden="true"></i><?= e(t('demo.info_private', 'stays private')) ?></span>
                                        <?php endif; ?>
                                    </dt>
                                    <dd><?= $field['value'] !== '' ? e($field['value']) : '<span class="demo-empty">' . e(t('demo.info_empty', 'not filled in yet')) . '</span>' ?></dd>
                                </div>
                            <?php endforeach; ?>
                        </dl>
                        <p class="form-hint"><?= e(t('demo.info_note', 'The same editor holds the name, the description, the photos and the status. Nothing on the printed tag has to change, and the address of the page never moves.')) ?></p>
                    </div>

                    <p class="demo-actions">
                        <a class="btn btn-primary btn-lg" href="<?= e($infoEditUrl) ?>">
                            <i class="fa-solid fa-pen-to-square" aria-hidden="true"></i>
                            <?= e(t('demo.info_open_editor', 'Open the editor')) ?>
                        </a>
                        <a class="btn btn-ghost btn-lg" href="#step-6"><?= e(t('demo.next', 'Next step')) ?></a>
                    </p>
                </div>

                <div class="demo-visual">
                    <?php if ($infoImage !== null): ?>
                        <figure class="product-shot"><img src="<?= e($infoImage) ?>" alt="<?= e($infoEntry['name']) ?>" loading="lazy"></figure>
                    <?php endif; ?>
                    <div class="demo-note">
                        <h3><?= e(t('demo.info_page_title', 'The page this code opens')) ?></h3>
                        <p><code><?= e($infoUrl) ?></code></p>
                        <p class="form-hint"><?= e(t('demo.info_page_note', 'Live, not a screenshot. Open it on a phone and the same fields appear.')) ?></p>
                        <p class="demo-actions">
                            <a class="btn btn-ghost" href="<?= e($infoUrl) ?>" target="_blank" rel="noopener">
                                <?= e(t('demo.open_new_tab', 'Open in a new tab')) ?>
                                <i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>

            <?php /*
             * The same idea, other jobs. Every tile opens a real page from the
             * demo account, so none of this is a drawing of a feature.
             */ ?>
            <?php
            $otherJobs = [
                ['entry' => 'lanyard', 'title' => t('demo.job_pass_title', 'Which visitor pass is still out'), 'body' => t('demo.job_pass_body', 'A tap at the desk shows the pass and who is holding it, so the paper list stops mattering.')],
                ['entry' => 'mini_tag', 'title' => t('demo.job_tool_title', 'Which tool lives in the box'), 'body' => t('demo.job_tool_body', 'A label the size of a fingernail names the tool and where it belongs.')],
                ['entry' => 'wristband', 'title' => t('demo.job_band_title', 'Which booking a band belongs to'), 'body' => t('demo.job_band_body', 'At the gate a single tap matches the guest to the booking.')],
                ['entry' => 'pet', 'title' => t('demo.job_pet_title', 'The one tag that keeps the finder form'), 'body' => t('demo.job_pet_body', 'A lost pet is the case where a stranger really does have to reach the owner.')],
            ];
            ?>
            <h3 class="demo-more-title"><?= e(t('demo.jobs_title', 'The same tag, other jobs')) ?></h3>
            <div class="grid demo-jobs">
                <?php foreach ($otherJobs as $job): ?>
                    <?php
                    $jobEntry = dat_demo_entry($job['entry']);
                    if ($jobEntry === null) {
                        continue;
                    }
                    ?>
                    <div class="grid-item large-span-3 medium-span-6 small-span-12">
                        <div class="tile">
                            <h5><?= e($job['title']) ?></h5>
                            <p class="tile-body"><?= e($job['body']) ?></p>
                            <div class="tile-links">
                                <a class="text-link" href="<?= e(dat_tag_url($jobEntry['public_id'])) ?>">
                                    <i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i><b><?= e(t('demo.job_open', 'Open the live page')) ?></b>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </section>

        <section class="demo-stage" id="step-6" role="tabpanel" aria-labelledby="tab-step-6" tabindex="0">
            <div class="demo-grid">
                <div class="demo-copy">
                    <p class="eyebrow"><?= e(t('demo.step5_eyebrow', 'Step 6 of 6')) ?></p>
                    <h2><?= e(t('demo.step5_title', 'Your own tag, in a minute')) ?></h2>
                    <p><?= e(t('demo.step5_body', 'Scan the code with a phone, create one tag as a guest and keep it by registering. No app, no payment, nothing to install on the stand.')) ?></p>

                    <div class="demo-note">
                        <h3><?= e(t('demo.extras_title', 'Also built in')) ?></h3>
                        <ul class="tick-list">
                            <li><?= e(t('demo.extra_wifi', 'A guest Wi-Fi code for menu boards and posters, printable next to the menu code')) ?></li>
                            <li><?= e(t('demo.extra_whatsapp', 'An optional WhatsApp button, or a chip that opens WhatsApp directly')) ?></li>
                            <li><?= e(t('demo.extra_eu', 'Hosted in Germany, asset details public, owner details never')) ?></li>
                        </ul>
                    </div>

                    <p class="demo-actions">
                        <a class="btn btn-primary btn-lg" href="<?= e(dat_url('start')) ?>">
                            <?= e(t('start.title', 'Start with one tag')) ?>
                        </a>
                        <a class="btn btn-ghost btn-lg" href="<?= e(dat_url('use-cases')) ?>">
                            <?= e(t('home.cta_products', 'See the products')) ?>
                        </a>
                    </p>
                </div>

                <div class="demo-visual">
                    <div class="demo-qr">
                        <?= dat_qr_svg(dat_url('start'), 6, 3) ?>
                        <p><?= e(t('demo.step5_qr_note', 'Scan to create your own tag')) ?></p>
                    </div>
                    <?php if ($wifiPayload !== null): ?>
                        <div class="demo-qr demo-qr-small">
                            <?= dat_qr_svg($wifiPayload, 5, 3) ?>
                            <p><?= e(t('demo.wifi_note', 'The same product idea for venues: a guest Wi-Fi code')) ?></p>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </section>
    </div>

    <footer class="demo-nav">
        <span class="demo-brand"><?= e(PORTAL_NAME) ?></span>
        <span class="demo-nav-hint"><?= e(t('demo.keyboard_hint', 'Arrow keys move between the steps')) ?></span>
    </footer>
</main>
<?php
dat_page_end(['footer' => false]);
